dataSource:
  mongodb:
    enabled: false
    uri: mongodb://root:password@localhost:27017
    # target: yahoo
  elasticsearch:
    enabled: false
    uri: http://localhost:9200
analysis:
  output:
    # baseFolder: tmp
    file:
      enabled: true
    elasticsearch:
      enabled: false
tickers:
  symbols:
    - bull:
        id: TQQQ
      bear:
        id: SQQQ
    - bull:
        id: SOXL
      bear:
        id: SOXS
    - bull:
        id: SPXL
      bear:
        id: SPXS
    - bull:
        id: LABU
      bear:
        id: LABD
    - bull:
        id: TNA
      bear:
        id: TZA
    - bull:
        id: YINN
      bear:
        id: YANG
    - bull:
        id: UDOW
      bear:
        id: SDOW
