dataSource:
  mongodb:
    enabled: false
    uri: mongodb://root:password@localhost:27017
    # target: yahoo
  elasticsearch:
    enabled: false
    uri: http://localhost:9200
  grafana:
    enabled: false
    uri: http://localhost:8091
    auth: Basic YWRtaW46cGFzc3dvcmQ=
    target: 77T92WEnz
platform:
  yahoo:
    uri: "wss://streamer.finance.yahoo.com/"
trade:
  # enable trade for consume, always do trade on replay
  enabled: true
  options:
  - symbols: [] # default
    validateIncreasedProfit: true
    ignoreZeroOrder: true
    enableProfitTake: true
    enableEarlyClear: true
    enableLossClear: true
    enableCloseTrade: true
    maxOrderAmount: 500
    profitTakeRate: 0.005
    earlyClearRate: 0.0

  flash:
    lossMarginRate: 0.005
    rules:
    - mode: Permit
      evaluation: false # default false, true to evaluate in log only
      trends:
      - { to: m0010, trend: Upward, up: '1', down: '1+' }
      - { to: m0030, trend: Downward }
      - { to: m0060, trend: Downward }
      deviations:
      - { to: m0070, value: 0.003 }
      oscillations:
      - { to: m0070, value: 0.013 }

  slug:
    lossMarginRate: 0.003
    rules:
    - mode: Permit
      trends:
      - { to: m0060, trend: Upward, up: '1', down: 1+ }
      - { to: m0030, trend: Upward }
      - { to: m0010, trend: Upward }
      deviations:
      - { to: m0120, value: 0.002 }
      oscillations:
      - { to: m0300, value: 0.008 }
    - mode: Permit
      symbols: [ LABU, LABD ]
      trends:
      - { to: m0060, trend: Upward, up: '1', down: 1+ }
      - { to: m0030, trend: Upward }
      - { to: m0010, trend: Upward }
      deviations:
      - { to: m0120, value: 0.002 }
      oscillations:
      - { to: m0300, value: 0.008 }

  revert:
    rules:
    - mode: Permit
      trends:
      - { to: m0030, trend: Upward }
      - { to: m0010, trend: Upward }
      deviations:
      - { to: m0120, value: 0.002 }
replay:
  exports:
    - { name: protfolio, enabled: false }
    - { name: slope,     enabled: false }
    - { name: trade,     enabled: false }
    - { name: message,   enabled: false }
    - { name: order,     enabled: true }
  outputs:
    file:
      enabled: false
    elasticsearch:
      enabled: false
units:
  - { name: m0010, duration: 10,   period: 360 }
  - { name: m0030, duration: 30,   period: 120 }
  - { name: m0060, duration: 60,   period: 60  }
  - { name: m0120, duration: 120,  period: 30  }
  - { name: m0180, duration: 180,  period: 15  }
  - { name: m0240, duration: 240,  period: 15  }
  - { name: m0300, duration: 300,  period: 12  }
  - { name: m0600, duration: 600,  period: 9   }
  - { name: m1200, duration: 1200, period: 6   }
  - { name: m1800, duration: 1800, period: 4   }
  - { name: m3600, duration: 3600, period: 3   }
tickers:
  symbols:
    - { bull: { id: TQQQ }, bear: { id: SQQQ } }
    - { bull: { id: SOXL }, bear: { id: SOXS } }
    - { bull: { id: SPXL }, bear: { id: SPXS } }
    - { bull: { id: LABU }, bear: { id: LABD } }
    - { bull: { id: TNA  }, bear: { id: TZA  } }
    - { bull: { id: YINN }, bear: { id: YANG } }
    - { bull: { id: UDOW }, bear: { id: SDOW } }
