{
 "title": "Daily Trend",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "TQQQ",
   "type": "graph",
   "description": "ProShares UltraPro QQQ",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: TQQQ AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: TQQQ AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: TQQQ AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: TQQQ AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "SQQQ",
   "type": "graph",
   "description": "ProShares UltraPro Short QQQ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: SQQQ AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SQQQ AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SQQQ AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SQQQ AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "SOXL",
   "type": "graph",
   "description": "Direxion Daily Semiconductor Bull 3X Shares",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: SOXL AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SOXL AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SOXL AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SOXL AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "SOXS",
   "type": "graph",
   "description": "Direxion Daily Semiconductor Bear 3X Shares",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: SOXS AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SOXS AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SOXS AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SOXS AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "SPXL",
   "type": "graph",
   "description": "Direxion Daily S&P500 Bull 3X Shares",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: SPXL AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SPXL AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SPXL AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SPXL AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "SPXS",
   "type": "graph",
   "description": "Direxion Daily S&P 500 Bear 3X Shares",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: SPXS AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SPXS AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SPXS AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SPXS AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "LABU",
   "type": "graph",
   "description": "Direxion Daily S&P Biotech Bull 3X Shares",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: LABU AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: LABU AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: LABU AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: LABU AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "LABD",
   "type": "graph",
   "description": "Direxion Daily S&P Biotech Bear 3X Shares",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: LABD AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: LABD AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: LABD AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: LABD AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "TNA",
   "type": "graph",
   "description": "Direxion Daily Small Cap Bull 3X Shares",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: TNA AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: TNA AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: TNA AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: TNA AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "TZA",
   "type": "graph",
   "description": "Direxion Daily Small Cap Bear 3X Shares",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: TZA AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: TZA AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: TZA AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: TZA AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "YINN",
   "type": "graph",
   "description": "Direxion Daily FTSE China Bull 3X Shares",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: YINN AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: YINN AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: YINN AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: YINN AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "YANG",
   "type": "graph",
   "description": "Direxion Daily FTSE China Bear 3X Shares",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 45 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: YANG AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: YANG AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: YANG AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: YANG AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "UDOW",
   "type": "graph",
   "description": "ProShares UltraPro Dow30",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: UDOW AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: UDOW AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: UDOW AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: UDOW AND period_type: 0",
     "timeField": "time"
    }
   ]
  },
  {
   "title": "SDOW",
   "type": "graph",
   "description": "ProShares UltraPro Short Dow30",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 54 },
   "yaxes": [
    { "format": "currencyUSD" }
   ],
   "targets": [
    {
     "alias": "Regular Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": { "sigma": 4 },
       "type": "extended_stats"
      }
     ],
     "query": "id: SDOW AND market_hours: RegularMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "PreMarket Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SDOW AND market_hours: PreMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Post Market Price - {{metric}}",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "price",
       "id": "1",
       "meta": {
        "avg": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SDOW AND market_hours: PostMarket AND period_type: 0",
     "timeField": "time"
    },
    {
     "alias": "Volume",
     "bucketAggs": [
      { "field": "time", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "volume",
       "id": "1",
       "meta": {
        "avg": false,
        "sum": true
       },
       "pipelineAgg": "select metric",
       "settings": {},
       "type": "extended_stats"
      }
     ],
     "query": "id: SDOW AND period_type: 0",
     "timeField": "time"
    }
   ]
  }
 ]
}